In [1]:
#DX = 0,1 2+4005+90 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.append(np.array((2,3)),np.arange(4,data.shape[1]))] #取出ecxel的2,3,4~最後 [1]為colume [0]為row

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 26
max score: 0.584795
[ True False False ..., False False False]
(array([   0,  164,  333,  419,  512,  578,  694,  849, 1248, 1287, 1351,
       1576, 1908, 1911, 2052, 2059, 2450, 2729, 2870, 3157, 3338, 3434,
       3647, 4050, 4084, 4085], dtype=int64),)
cost time：143541.285811


In [3]:
#DX = 0,1 2+4005+90 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((2,  166,  335,  421,  514,  580,  696,  851, 1250, 1289, 1353,
       1578, 1910, 1913, 2054, 2061, 2452, 2731, 2872, 3159, 3340, 3436,
       3649, 4052, 4086, 4087))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 26
max score: 0.970760
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int64),)
cost time：14.2624667545


In [5]:
#DX = 0,1 2+4005+90 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((166,  335,  421,  514,  580,  696,  851, 1250, 1289, 1353,
       1578, 1910, 1913, 2054, 2061, 2452, 2731, 2872, 3159, 3340, 3436,
       3649))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 22
max score: 0.836257
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21], dtype=int64),)
cost time：11.8981475263
