In [1]:
#DX = 0,1 2+4005 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.append(np.array((2,3)),np.arange(4,4009))] #取出ecxel的2,3,4005 [1]為colume [0]為row

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 16
max score: 0.649123
[ True False False ..., False False False]
(array([   0,  164,  215,  709,  736, 1287, 1501, 2059, 2729, 2953, 3065,
       3157, 3283, 3316, 3434, 3809], dtype=int64),)
cost time：146487.495816


In [2]:
#DX = 0,1 2+4005 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((2,  166,  217,  711,  738, 1289, 1503, 2061, 2731, 2955, 3067, 3159, 3285, 3318, 3436, 3811))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 16
max score: 0.888889
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=int64),)
cost time：9.72846197005


In [3]:
#DX = 0,1 2+4005 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((166,  217,  711,  738, 1289, 1503, 2061, 2731, 2955, 3067, 3159, 3285, 3318, 3436, 3811))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 14
max score: 0.883041
[ True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14], dtype=int64),)
cost time：8.05259773682


In [4]:
#DX = 0,1 2+4005 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((166,  217,  711,  738, 1289, 1503, 2061, 2731, 2955, 3067, 3159, 3285, 3436, 3811))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 14
max score: 0.883041
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int64),)
cost time：7.50032902948
