In [1]:
#DX = 0,1 2+4005 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.append(np.array((2,3)),np.arange(4,4009))] #取出ecxel的2,3,4005 [1]為colume [0]為row

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 25
max score: 0.643275
[ True False False ..., False False False]
(array([   0,   53,  164,  486,  492,  688,  709,  877, 1194, 1248, 1273,
       1371, 1383, 1441, 1526, 2069, 2229, 2450, 2729, 2955, 3157, 3283,
       3434, 3715, 3777], dtype=int64),)
cost time：77025.7413928


In [24]:
#DX = 0,1 2+4005 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((2,   55,  166,  488,  494,  690,  711,  879, 1196, 1250, 1275,
                   1373, 1385, 1443, 1528, 2071, 2231, 2452, 2731, 2957, 3159, 3285,
                   3436, 3717, 3779))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 24
max score: 0.976608
[ True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int64),)
cost time：36.5812115574


In [25]:
#DX = 0,1 2+4005 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((2,   55,  166,  488,  494,  690,  711,  879, 1196, 1250, 1275,
                   1373,    1443, 1528, 2071, 2231, 2452, 2731, 2957, 3159, 3285,
                   3436, 3717, 3779))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 24
max score: 0.976608
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64),)
cost time：34.9498691562


In [26]:
#DX = 0,1 2+4005 no normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((   55,  166,  488,  494,  690,  711,  879, 1196, 1250, 1275,
                   1373,    1443, 1528, 2071, 2231, 2452, 2731, 2957, 3159, 3285,
                   3436, 3717, 3779))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 23
max score: 0.912281
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22], dtype=int64),)
cost time：27.7046959511
