In [1]:
#DX = 0,1 2+4005+90 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.append(np.array((2,3)),np.arange(4,data.shape[1]))] #取出ecxel的2,3,4~最後 [1]為colume [0]為row

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 18
max score: 0.678363
[ True False False ..., False False False]
(array([   0,  164,  578,  709,  736,  926, 1051, 1101, 1286, 1350, 1383,
       1577, 2123, 2705, 2994, 3157, 3338, 3956], dtype=int64),)
cost time：91145.2131138


In [2]:
#DX = 0,1 2+4005+90 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((2,  166,  580,  711,  738,  928, 1053, 1103, 1288, 1352, 1385,
       1579, 2125, 2707, 2996, 3159, 3340, 3958))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 18
max score: 0.853801
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int64),)
cost time：19.7237103926


In [3]:
#DX = 0,1 2+4005+90 normal
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

X=data[:, np.array((166,  580,  711,  738,  928, 1053, 1103, 1288, 1352, 1385,
       1579, 2125, 2707, 2996, 3159, 3340, 3958))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = X / X.max(axis=0)
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Optimal number of features : 17
max score: 0.847953
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16], dtype=int64),)
cost time：19.1546179629
