In [6]:
import pandas as pd
import numpy as np
import time
starttime = time.clock() 
test = pd.read_csv('joint_all.csv')
test=test[(test.DX == 0) | (test.DX == 1)] #取出DX為0跟1的case
data=test.as_matrix() #將test存成矩陣

#X=data[:, np.append(np.array((2,3)),np.arange(4009,data.shape[1]))] #取出ecxel的2,3,4010~最後 [1]為colume [0]為row
#X=data[:, np.array((2,4055,4084,4086,4087,4091))]

#X=data[:, np.arange(2,data.shape[1])] #取出2,3,4005+90筆
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390,  421,  488,
        509,  514,  546,  580,  706,  711,  879,  955, 1053, 1103, 1250,
       1275, 1289, 1302, 1334, 1353, 1373, 1385, 1443, 1511, 1528, 1769,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
       2955, 2957, 3019, 3145, 3159, 3231, 3254, 3285, 3318, 3403, 3424,
       3436, 3446, 3504, 3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1103, 1250,
       1275, 1289    , 1334, 1353, 1373, 1385, 1443, 1511, 1528, 1769,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
       2955, 2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436, 3446, 3504, 3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1289    , 1334, 1353, 1373, 1385, 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436, 3446, 3504, 3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1289    , 1334, 1353, 1373 , 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436, 3446, 3504, 3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1289    , 1334, 1353, 1373 , 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436 , 3504, 3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((2,116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1289    , 1334, 1353, 1373 , 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436 ,  3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
'''X=data[:, np.array((116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1289    , 1334, 1353, 1373 , 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436 ,  3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]'''
X=data[:, np.array((116,  166,  178,  190,  217,  235,  335,  390     ,  488,
            509,  514,  546,  580,  706,  711,  879,  955    , 1250,
       1275, 1353, 1373 , 1443, 1511 ,
       1910, 1958, 2054, 2061, 2071, 2445, 2707, 2731, 2758, 2852, 2949,
        2957, 3019    , 3159, 3231, 3254, 3285, 3318, 3403    ,
       3436 ,  3511, 3552, 3649, 3717, 3744, 3779, 3788, 3811,
       3978))]

y=data[:,1] #取出DX那一行
X[np.isnan(X)]=0 #把 nan改成0
X_normed = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X = X_normed

#將X y隨機排序
randsort=np.argsort(np.random.rand(y.size)) 
X=X[randsort]
y=y[randsort]

from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.svm import SVC
from sklearn.cross_validation import LeaveOneOut
from sklearn.cross_validation import cross_val_score
from sklearn import svm, metrics

svc = SVC(kernel="linear")
rfecv = RFECV(estimator=svc, step=1, cv=LeaveOneOut(171), scoring='accuracy')
rfecv.fit(X, y)
print("Optimal number of features : %d" % rfecv.n_features_)
print("max score: %f" % np.max(rfecv.grid_scores_))
print rfecv.support_
print np.nonzero(rfecv.support_)

'''score=cross_val_score(svc,X,y,scoring='accuracy', cv=LeaveOneOut(171))
print(np.mean(score))'''


'''n_samples = len(y)
classifier = SVC(kernel="linear")

# 用前半部份的資料來訓練
classifier.fit(X[:n_samples / 2], y[:n_samples / 2])
# Now predict the value of the digit on the second half:
expected = y[n_samples / 2:]
#利用後半部份的資料來測試分類器
predicted = classifier.predict(X[n_samples / 2:])

print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
'''

endtime = time.clock() 
print("cost time：%s" %(endtime-starttime))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99        46
        1.0       1.00      0.97      0.99        40

avg / total       0.99      0.99      0.99        86


Confusion matrix:
[[46  0]
 [ 1 39]]
cost time：0.415616507914


In [5]:
X = np.array([[1.1,2,3.5],[3,4.8,5],[5.2,6,7.6],[7.4,8.5,9.7]])
print (X.shape)

(4L, 3L)


In [6]:
print(X)

[[ 1.1  2.   3.5]
 [ 3.   4.8  5. ]
 [ 5.2  6.   7.6]
 [ 7.4  8.5  9.7]]


In [7]:
X_normed = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X = X_normed

In [8]:
print(X)

[[ 0.          0.          0.        ]
 [ 0.3015873   0.43076923  0.24193548]
 [ 0.65079365  0.61538462  0.66129032]
 [ 1.          1.          1.        ]]
